export const searchTypes = {
  SET_CURRENT_CITY: 'SET_CURRENT_CITY',
  FETCH_FILMS: 'FETCH_FILMS',
  SET_CURRENT_FILM_NAME: 'SET_CURRENT_FILM_NAME',
  SET_SESSION_DATE: 'SET_SESSION_DATE',
  SET_CURRENT_CINEMA: 'SET_CURRENT_CINEMA',
  GET_FILTRED_FILM_LIST: 'GET_FILTRED_FILM_LIST',
  GET_FILM_BY_ID: 'GET_FILM_BY_ID',
  SET_CHOSEN_FILM_ID: 'SET_CHOSEN_FILM_ID',
  SET_COUNT_OF_SEATS: 'SET_COUNT_OF_SEATS',
};

export const userTypes = {
  SET_LOCATION: 'SET_LOCATION',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILD: 'SIGN_IN_FAILD',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILD: 'SIGN_UP_FAILD',
  LOGOUT_USER: 'LOGOUT_USER',
  RESET_ERROR_MESSAGE: 'RESET_ERROR_MESSAGE',
};

export const seatsSelectionTypes = {
  GET_SESSION_BY_ID: 'GET_SESSION_BY_ID',
};

export const orderTypes = {
  ADD_ORDER: 'ADD_ORDER',
  FETCH_ORDERS: 'FETCH_ORDERS',
};
