export const searchTypes = {
  SET_CURRENT_CITY: 'SET_CURRENT_CITY',
  FETCH_FILMS: 'FETCH_FILMS',
  SET_CURRENT_FILM_NAME: 'SET_CURRENT_FILM_NAME',
  SET_SESSION_DATE: 'SET_SESSION_DATE',
  SET_CURRENT_CINEMA: 'SET_CURRENT_CINEMA',
  GET_FILTRED_FILM_LIST: 'GET_FILTRED_FILM_LIST'
};

export const userTypes = {
  SET_LOCATION: 'SET_LOCATION'
};